### ISSUE TITLE
CLI Arguments cp.jl file not working

### ISSUE THREAD

**Issue by korbinian90** [ninjaaron/administrative-scripting-with-julia#1]
For "CLI Arguments", don't you need a shebang in the beginning of the cp.jl file?
I added `#!/usr/bin/env julia` as a first line, using chmod u+x on it,
than it could run it.

However, it failed with:
ERROR: LoadError: ArgumentError: 'somefolder' exists. `force=true` is required to remove 'somefolder' before copying.

I solved it by using the full path for cp:
`cp(src, joinpath(dest, basename(src)))`

**Comment by ninjaaron** [comment]
Thanks for opening the issue. I'll look into it further. May I ask what platform you're on?

**Comment by korbinian90** [comment]
Ubuntu 16.04 with Julia 1.0.1
