### ISSUE TITLE
CLI notebook cannot be displayed in github

### ISSUE THREAD

**Issue by tk3369** [ninjaaron/administrative-scripting-with-julia#5]
It seems to be a problem with the recent commit. The prior version works fine.

<img width="1243" alt="Screen Shot 2020-09-28 at 12 24 37 AM" src="https://user-images.githubusercontent.com/1159782/94402607-1f8fd300-0121-11eb-8f6e-cfa616fd3a07.png">

**Comment by ninjaaron** [comment]
Thanks for reporting this. Looks like @kescobo forgot a comma. This is why we don't edit JSON by hand. :man_facepalming:

fixed by https://github.com/ninjaaron/administrative-scripting-with-julia/commit/38f1f1d7e98587a076521cd645928dbf68912401
