### ISSUE TITLE
Embarassing typo in main page, aka readme: Lisp as Lips.  8 ]

### ISSUE THREAD

**Issue by libweirdness** [ninjaaron/administrative-scripting-with-julia#6]
in the main readme page
https://github.com/ninjaaron/administrative-scripting-with-julia

the word "Lisp" is mis-spelt as "Lips".

Please fix that.

---

PS: thank you for making this:
I've realized that Julia *needs* to be taught with algebra, statistics, trig, geometry, & especially calculus,
so therefore it needs to be the fundamental programming language taught in school.

There is no justification for having both Julia & some other language required, for students to have to learn, if Julia can do enough, well-enough...

For a more-complete set, I think

* Julia ( Math is required, therefore Julia is required.  Period. )
* Ruby ( true OOP, whereas Java, etc, is Class-Hierarchy Oriented Programming: which is *brittle* )
* Haskell ( look up "Algebra-Driven Design" for the perfection of its potential )
* Prolog+Logic, together
* Rust, for low-level stuff ( please, World, make C redundant: as much as it suits me, it is the wrong answer )

This work of yours is the only useful work on 1 of the key requirements for this paradigm-change.

Salut, Namaste, & Kaizen, eh?

( :

**Comment by ninjaaron** [comment]
Thanks for the correction and the encouragement!
